---

- name: Docker key
  apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    state: present

- name: Add docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
    update_cache: yes
    state: present

- name: Finally install docker from repo
  apt:
    name: docker-ce
    update_cache: yes
    state: present

- name: Create docker group
  group:
    name: docker
    state: present

- name: Add jenkins user to docker user group
  user:
    name: "{{ansible_user_id}}"
    groups: docker
    append: yes